### ISSUE TITLE
@display_handle of Fancyline::Widget::HistorySearch must be Int32, not UInt64

### ISSUE THREAD

**Issue by srcrip** [Papierkorb/fancyline#1]
I was starting a new project with fancyline but ran into errors. So I tried the example like this and  they persisted:

Source:
```crystal
require "../lib/fancyline/src/fancyline"

fancy = Fancyline.new # Build a shell object
puts "Press Ctrl-C or Ctrl-D to quit."

while input = fancy.readline("$ ") # Ask the user for input
  # Also note how the history already works!
  system(input) # And run it
end
```

Traceback:
```crystal
❯ crystal src/test.cr 

Error in src/test.cr:3: instantiating 'Fancyline:Class#new()'

fancy = Fancyline.new # Build a shell object
                  ^~~

in lib/fancyline/src/fancyline.cr:41: instantiating 'initialize(IO::FileDescriptor, IO::FileDescriptor)'

  def initialize(@input = STDIN, @output = STDOUT)
  ^

in lib/fancyline/src/fancyline.cr:43: instantiating 'Fancyline::KeyAction:Class#new()'

    @actions = KeyAction.new
                         ^~~

in lib/fancyline/src/fancyline/key_action.cr:56: instantiating 'Fancyline::Context#start_widget(Fancyline::Widget::HistorySearch)'

        ctx.start_widget(Widget::HistorySearch.new)
            ^~~~~~~~~~~~

in lib/fancyline/src/fancyline/context.cr:64: instantiating 'Fancyline::Widget::HistorySearch#start(Fancyline::Context)'

      widget.start self
             ^~~~~

in lib/fancyline/src/fancyline/widget/history_search.cr:25: instance variable '@display_handle' of Fancyline::Widget::HistorySearch must be Int32, not UInt64

        @display_handle = ctx.fancyline.display.add do |ctx, line, yielder|
        ^~~~~~~~~~~~~~~
```

Any time I use `Fancyline.new` I get that same error about @display_handle.

This is my Crystal version:
```bash
❯ crystal --version

Crystal 0.24.1 (2017-12-20)

LLVM: 5.0.0
Default target: x86_64-unknown-linux-gnu
```

**Comment by Papierkorb** [comment]
Hi,

`cute` had an update somewhat recently which changed the API slightly (Causing compile-time errors if hit). That change was in Cute v0.3.1, reflected in commit https://github.com/Papierkorb/fancyline/commit/ad478b1cd1cf022ebd1315b40ea280554ae5a9c6 in Fancyline.

Can you check if your copy of the `cute` shard in `lib/` is of version 0.3.1?

**Comment by srcrip** [comment]
Appears to be:
```
❯ cat shard.yml 

name: cute
version: 0.3.1

```

**Comment by Papierkorb** [comment]
Oh, now I see. I haven't pushed a version for quite some time. Bummer.

Your hotfix would be to add `branch: master` to the fancyline dependency, that should take care of it until I pushed the version in 5 minutes.

**Comment by srcrip** [comment]
Thanks @Papierkorb!

**Comment by Papierkorb** [comment]
So, Version 0.2.0 pushed, renamed the v0.1 tag to v0.1.0 (TL;DR: Work-around shards bug), and a test app worked for me.

Can you retry, and if it works for you, close? Thanks

**Comment by srcrip** [comment]
Confirmed working great now. Thanks!
