### ISSUE TITLE
Mismatched versions

### ISSUE THREAD

**Issue by yb66** [Papierkorb/fancyline#10]
Hi there,

I'm just getting to know the project but it looks really useful, thanks 🙏 

I'm using this with Crystal v1.0.0 and I notice another issue has someone who is using it with v1 too, so perhaps an update to the shard.yml would be in order? Perhaps:

    crystal: ">= 0.35.1, < 2.0.0"

It'd remove those scary/vexing messages on `shards install`.

The library version inside the shard also doesn't match that of master or the v0.3.3 tag. I've seen this in a few libs lately so I'll mention it on the Crystal forum, not sure what the point of a version number is if git tags are the true point of reference… I'll see what people think, it's clearly a pain point, maybe something can be done.

Anyway, I'm sure I'll have some questions to bother you with 😅 

Thanks again.

Regards,
iain

**Comment by lagerfeuer** [comment]
Hey @yb66,

thanks for bringing this up! I'll take a look, I tried to go the path of least resistance, but the cute dependency hasn't been updated either. Don't know how much time I'll have for that since I'm pretty occupied with work ATM.

**Comment by lagerfeuer** [comment]
Opened a PR for cute: Papierkorb/cute#3

**Comment by lagerfeuer** [comment]
@yb66 no updated, both fancyline and its dependency cute. Use version 0.4.0 going forward :)

**Comment by yb66** [comment]
You, sir,  are a scholar and a gentleman!
